### ISSUE TITLE
Error in Purescript compilation

### ISSUE THREAD

**Issue by liminalisht** [alexmingoia/pux-starter-app#23]
I cloned the repo and followed the instructions, but I get some errors when I run `npm start`:

```
$ npm start

> pux-starter-app@8.0.0 start /Users/liminalisht/dev/pux-starter-app
> npm run watch

> pux-starter-app@8.0.0 watch /Users/liminalisht/dev/pux-starter-app
> npm run clean && node ./webpack.config.js

> pux-starter-app@8.0.0 clean /Users/liminalisht/dev/pux-starter-app
> rimraf static/dist && rimraf dist && rimraf output

Compiling PureScript...
Finished compiling PureScript.
webpack built 410088aac3d888a25cd4 in 1205ms

ERROR in PureScript compilation:
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/liminalisht/dev/pux-starter-app/node_modules/purescript/vendor/psc ENOENT
    at exports._errnoException (util.js:893:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:148:18)
    at node.js:405:3

ERROR in ./src/Main.purs
Module build failed:
 @ ./support/index.js 1:11-38

ERROR in ./src/Layout.purs
Module build failed:
 @ ./support/index.js 2:19-48
webpack: bundle is now VALID.
```

I see that there is another issue where the recommendation is to use v. 5 of node, b/c there are issues with v6 and purescript generally. However, I am using v. 5.12.0

**Comment by sleexyz** [comment]
I get the same error with node v.6.4.0

**update** Fixed by deleting `~/.npm`, `node_modules`
I also removed the dependency on `purescript` in `package.json` as to use the system-wide psc provided by my package manager ( i use NixOS)

**Comment by alexmingoia** [comment]
Issues with node 6 should be fixed in `9.0.0`

**Comment by dmvianna** [comment]
This is still happening in `9.0.0`. I tested node versions `7.2.0`, `6.9.1`, `5.9.1`, `4.6.2`.
